### ISSUE TITLE
"Connection closed" Puppeteer error after inactivity

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/remix-og-image#8]
When developing with the plugin turned out, the app crashes sometimes because Puppeteer goes to sleep:

```
/node_modules/.pnpm/wrangler@3.57.1_@cloudflare+workers-types@4.20240512.0/node_modules/wrangler/wrangler-dist/cli.js:29749
            throw a;
            ^

Error: Protocol error: Connection closed.
    at Connection._rawSend (file:///Users/kettanaito/Documents/web/vite-remix-og-image-plugin/node_modules/.pnpm/puppeteer-core@23.1.0/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:84:35)
    at Connection.send (file:///Users/kettanaito/Documents/web/vite-remix-og-image-plugin/node_modules/.pnpm/puppeteer-core@23.1.0/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:77:21)
    at CdpBrowser._createPageInContext (file:///Users/kettanaito/Documents/web/vite-remix-og-image-plugin/node_modules/.pnpm/puppeteer-core@23.1.0/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:177:53)
    at CdpBrowserContext.newPage (file:///Users/kettanaito/Documents/web/vite-remix-og-image-plugin/node_modules/.pnpm/puppeteer-core@23.1.0/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/BrowserContext.js:112:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CdpBrowser.newPage (file:///Users/kettanaito/Documents/web/vite-remix-og-image-plugin/node_modules/.pnpm/puppeteer-core@23.1.0/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Browser.js:174:16)
    at async file:///Users/kettanaito/Documents/web/vite-remix-og-image-plugin/build/plugin.js:129:22
    at async Promise.all (index 0)
    at async generateOpenGraphImages (file:///Users/kettanaito/Documents/web/vite-remix-og-image-plugin/build/plugin.js:127:5)
```

**Comment by kettanaito** [comment]
Also fixed by #12 since Puppeteer is no longer running for an indefinite amount of time.
